keys:
  - &noteed age1jydee60ssqkgd2uayarrar7ndudst4ey2mpm580n0vkswkea7v5sawgmxj
  - &vault age1k5nwc7annjte803x787v6vmvffr5vxshf4wxfkuslww2cq427y4sxfrm9a
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *noteed
      - *vault
