name: deployment
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Checkout this repository
      uses: actions/checkout@v2
    - name: Set unfree (for FAHClient)
      run: echo "NIXPKGS_ALLOW_UNFREE=1" >> $GITHUB_ENV
    - name: Build the toplevel
      run: nix-build --attr toplevel
    - name: The toplevel Nix store path is
      run: |
        echo $(readlink ./result) | tee test.txt
    - run: 'echo "$CACHE_SIGNING_KEY" > cache-priv-key.pem'
      shell: bash
      env:
        CACHE_SIGNING_KEY: ${{ secrets.CACHE_SIGNING_KEY }}
    - name: Sign the toplevel
      run: nix sign-paths --recursive --key-file cache-priv-key.pem $(readlink ./result)
    - name: Cache the result to S3 (Backblaze B2)
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.B2_APPKEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.B2_APPKEY }}
      run: |
        nix copy --to \
          's3://hypered-store/cache?endpoint=s3.eu-central-003.backblazeb2.com' \
          ./result
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install Backblaze B2 command-line tool
      run: |
        python -m pip install --upgrade pip
        pip install --quiet --no-cache-dir b2==2.0.2
    - name: Sync to Backblaze B2
      run: |
        b2 authorize-account ${{ secrets.B2_APPKEY_ID }} ${{ secrets.B2_APPKEY }}
        b2 upload_file hypered-store ./test.txt toplevels/test.txt
        b2 clear-account
